from PySide6.QtGui import QColor


class ThemeVariables:
    COLOR_BG = "#f3f4f6"
    COLOR_SURFACE = "#ffffff"
    COLOR_BORDER = "#e5e7eb"
    COLOR_TEXT = "#1f2937"
    COLOR_PRIMARY = "#8b5cf6"
    COLOR_ACCENT = "#a3e635"
    COLOR_RULER_BG = "#ffffff"
    COLOR_RULER_SAFE_MARGIN = "#e0e0e0"
    COLOR_LINE = "#dddddd"
    COLOR_TEXT_MUTED = "#888888"
    COLOR_TEXT_LIGHT = "#C2C2C2"
    COLOR_KEY_STROKE = "#000000"
    COLOR_KEY_FILL = "#000000"
    COLOR_PLAYHEAD = "#e74c3c"
    COLOR_HANDLE = "#000000"
    
    BG_COLOR = QColor(COLOR_BG)
    SURFACE_COLOR = QColor(COLOR_SURFACE)
    BORDER_COLOR = QColor(COLOR_BORDER)
    TEXT_COLOR = QColor(COLOR_TEXT)
    PRIMARY_COLOR = QColor(COLOR_PRIMARY)
    ACCENT_COLOR = QColor(COLOR_ACCENT)
    RULER_BG = QColor(COLOR_RULER_BG)
    RULER_SAFE_MARGIN = QColor(COLOR_RULER_SAFE_MARGIN)
    LINE_COLOR = QColor(COLOR_LINE)
    TEXT_MUTED = QColor(COLOR_TEXT_MUTED)
    TEXT_LIGHT = QColor(COLOR_TEXT_LIGHT)
    KEY_STROKE = QColor(COLOR_KEY_STROKE)
    KEY_FILL = QColor(COLOR_KEY_FILL)
    PLAYHEAD_COLOR = QColor(COLOR_PLAYHEAD)
    HANDLE_COLOR = QColor(COLOR_HANDLE)
    OVERLAY_COLOR = QColor(200, 200, 200, 60)
    
    LEFT_MARGIN = 100
    RIGHT_MARGIN = 30
    RULER_HEIGHT = 20
    TRACK_HEIGHT = 30
    TRACK_GAP = 5
    HANDLE_WIDTH = 2
    HANDLE_GRAB_MARGIN = 10
    KEY_SIZE = 5
    PLAYHEAD_WIDTH_RATIO = 0.5
    PLAYHEAD_LINE_WIDTH = 2
    CONTROL_BAR_HEIGHT = 40
    BUTTON_SIZE = 32
    BUTTON_HEIGHT = 30
    FONT_SIZE_NORMAL = 8
    FONT_SIZE_TIME = 11
    
    CONTROL_BAR_MARGIN = 10
    CONTROL_BAR_MARGIN_V = 5
    CONTROL_BAR_SPACING = 5
    TIMELINE_BOTTOM_PADDING = 20
    
    BUTTON_RADIUS = 4
    PLAYHEAD_RADIUS = 4
    PANEL_RADIUS = 16
